# Build stage
FROM node:20 AS build
WORKDIR /app

# Copy only dependency files from root (hmx/)
COPY package*.json ./

RUN npm install

# Copy everything else (src, vite.config.js, etc.)
COPY . .

# Build React app
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
